[package]
name = "cli-chess"
version = "0.1.0"
authors = ["Tim Matthias Jentzsch <tim.jentzsch@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.0"
pleco = "0.5.0"
rand = "0.6.5"
